baseURL = "https://krvdev.com"
languageCode = "en-us"
title = "Vishnu Deva"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  homeSubtitle = "Platform | ML"
  
  description = "My Tech Blog"
  keywords = "blog"

  defaultTheme = "dark"

  [taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

  [languages]
    [languages.en]
      copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
      readOtherPosts = "Read other posts"

      [languages.en.params.logo]
        logoText = "cd ~"
        logoHomeLink = "/"

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  # Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/VishDev12/"

  [[params.social]]
    name = "email"
    url  = "krvdev@outloook.com"
