baseURL = "https://krvdev.com"
languageCode = "en-us"
title = "Vishnu Deva"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "01-02-2006"
  dateformNumTime = "01-02-2006 15:04 -0700"

  homeSubtitle = "Platform | ML"
  enableSharingButtons = true
  
  description = "My tech blog"
  keywords = "homepage, blog"

  defaultTheme = "dark"

  [taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

  [languages]
    [languages.en]
      copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
      readOtherPosts = "Read other posts"

      [languages.en.params.logo]
        logoText = "cd ~"
        logoHomeLink = "/"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
